server:
  port: 80
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/weibo?serverTimezone=UTC
      username: root
      password: shiyu196
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


